- hosts: all
  become: yes
  become_user: root

  tasks:

    - name: "Check that /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.gz exists"
      stat:
        path: "/var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.gz"
      register: stat_result1

    - name: "Check that /usr/local/bin/k3s exists"
      stat:
        path: "/usr/local/bin/k3s"
      register: stat_result2

    - name: "Upload files"
      copy:
        src: "{{ item }}"
        dest: /root/
      with_fileglob:
      - ../files/*
      when: not stat_result1.stat.exists and not stat_result2.stat.exists

    - name: "Check sums & move K3s files in place"
      args:
        executable: /bin/sh
      shell: |
        cd /root
        cat sha256sum-install.sh.txt | sha256sum -c - && \
        cat sha256sum-k3s.txt | sha256sum -c - && \
        cat sha256sum-k3s-airgap-images-amd64.tar.gz.txt | sha256sum -c - && \
        mkdir -p /var/lib/rancher/k3s/agent/images/ && \
        cp k3s-airgap-images-amd64.tar.gz /var/lib/rancher/k3s/agent/images/ && \
        chmod +x k3s && \
        cp k3s /usr/local/bin/k3s
      register: shell_output1
      when: not stat_result1.stat.exists and not stat_result2.stat.exists
    - debug:
        var: shell_output1